CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Employees" (
    "Id" uuid NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Status" text NOT NULL,
    "Observations" text NOT NULL,
    "CreateAt" timestamp with time zone NOT NULL,
    "UpdateAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Employees_UserId" FOREIGN KEY ("UserId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text,
    "ProviderKey" text,
    "ProviderDisplayName" text,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_UserLogins_Employees_UserId" FOREIGN KEY ("UserId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Employees_UserId" FOREIGN KEY ("UserId") REFERENCES "Employees" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EmployeeEntityRole" (
    "RoleIdsId" uuid NOT NULL,
    "UserIdId" uuid NOT NULL,
    CONSTRAINT "PK_EmployeeEntityRole" PRIMARY KEY ("RoleIdsId", "UserIdId"),
    CONSTRAINT "FK_EmployeeEntityRole_Employees_UserIdId" FOREIGN KEY ("UserIdId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EmployeeEntityRole_Roles_RoleIdsId" FOREIGN KEY ("RoleIdsId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Employees_UserId" FOREIGN KEY ("UserId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('8cf9cba0-b0c1-4972-b621-2e474d84c732', NULL, 'User', 'USER');
INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('d24aaaf3-45b3-4698-91ab-58247d4383fc', NULL, 'Admin', 'ADMIN');

CREATE INDEX "IX_EmployeeEntityRole_UserIdId" ON "EmployeeEntityRole" ("UserIdId");

CREATE INDEX "EmailIndex" ON "Employees" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "Employees" ("NormalizedUserName");

CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");

CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241204054838_AddIdentityPrimaryKeys', '9.0.0');

COMMIT;

